name: birimfiyatlar
description: "A new Flutter project."
publish_to: 'none'
environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  flutter_social_button: ^1.1.6
  url_launcher: ^6.3.1
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.2.1
  flutter_lints: ^5.0.0
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - /Users/hasanefe/IdeaProjects/birimfiyatlar/assets/images/logo.png
    - token.env
    - assets/images/filter.png
    - assets/images/book.png
    - assets/images/logo-image.png

